# Generated by Django 5.0.7 on 2024-07-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('image_s', models.ImageField(blank=True, null=True, upload_to='products/small/', verbose_name='Image small')),
                ('image_m', models.ImageField(blank=True, null=True, upload_to='products/medium/', verbose_name='Image medium')),
                ('image_l', models.ImageField(blank=True, null=True, upload_to='products/large/', verbose_name='Image large')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='categories.subcategory', verbose_name='Sub category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
